---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову.
  - Пользователь должен иметь возможность искать товары по категории.
  - Пользователь должен иметь возможность фильтровать товары по цене.
  - Пользователь должен иметь возможность фильтровать товары по цвету.
  - Пользователь должен иметь возможность фильтровать товары по наличию.
  - Пользователь должен иметь возможность фильтровать товары по бренду.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Пользователь должен иметь возможность удалять товары из корзины.
  - Пользователь должен иметь возможность очистить корзину.
  - Пользователь должен иметь возможность сделать заказ товара. 
  - Пользователь должен иметь возможность перемещаться между страницами каталога.
  - Пользователь должен иметь возможность искать товары по хештегам.
  
продолжение покупок из корзины. Покупка. Заказы
Навигация по страницам каталога.
На странице товара есть хэштег с переходом в категорию - это тоже есть смысл проверить.

  - Сайт должен иметь версии на английском и русском языках.
